### ISSUE TITLE
ACM can't access GitHub repo

### ISSUE THREAD

**Issue by laurentgrangeau** [GoogleCloudPlatform/gke-securing-third-party-apps-blueprint#27]
When trying to configure the cluster through ASM, GKe cannot resolve the URL "https://github.com"
Here is the full stacktrace:
```
E0610 11:57:08.549173       1 controller.go:70] failed to get the commit hash and sync directory from the source directory /repo/source/rev: KNV2004: unable to sync repo
Error in the git-sync container: {"Msg":"too many failures, aborting","Err":"Run(git clone --no-checkout -b main --depth 1 https://github.com/GoogleCloudPlatform/gke-third-party-apps-blueprint /repo/source): exit status 128:{ stdout: \"\", stderr: \"Cloning into '/repo/source'...\\nfatal: could not read Username for 'https://github.com': No such device or address\\n\" }","Args":{"failCount":30}}

For more information, see https://g.co/cloud/acm-errors#knv2004
```

**Comment by ferrarimarco** [comment]
Hi @laurentgrangeau !

https://g.co/cloud/acm-errors#knv2004 suggest that it might be either an authentication (to the repo) issue, or a network misconfiguration. To me, and as you suggested, the former seems more likely. To confirm, can you try spinning up a (busybox?) Pod in the same namespace as the one where the Pod you got that error from runs, and try accessing (ping, cURL...) GitHub from there?

Thanks!
